version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ie-starter-kit-account"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1aouh97kkgbvz"
s3_prefix = "ie-starter-kit-account"
region = "us-east-2"
confirm_changeset = true
disable_rollback = true
parameter_overrides = [
    "ProjectName=ie-starter-kit",
]
capabilities =  ['CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', 'CAPABILITY_AUTO_EXPAND']
image_repositories = []
