# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  IntraEdege Starter Kit SAM Stack for Account Resource Deployment

Parameters:
  ProjectName:
    Description: Project Name
    Type: String
    MinLength: 5
    Default: ie-starter-kit

  GitHubOrg:
    Type: String
    Description: Organization Name in Git-Hub
    MinLength: 5
    Default: intraedge-services

  SAMRepository:
    Type: String
    Description: The name of the repository used for SAM
    MinLength: 5
    Default: reference-services-sam

  WebRepository:
    Type: String
    Description: The name of the repository used for web application
    MinLength: 5
    Default: reference-services-sam

Transform:
- AWS::Serverless-2016-10-31

Resources:
  OIDCDeployRoles:
    Type: AWS::Serverless::Application 
    Properties:
      TimeoutInMinutes: 5
      Location: resources/security/oidc-deploy-roles/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        GitHubOrg: !Ref GitHubOrg
        SAMRepository: !Ref SAMRepository
        WebRepository: !Ref WebRepository

  CertificateArnCustomFunction:
    Type: AWS::Serverless::Application 
    Properties:
      TimeoutInMinutes: 5
      Location: resources/custom-resources/certificate-arn/template.yaml
      Parameters:
          ProjectName: !Ref ProjectName

  WebACLArnCustomFunction:
    Type: AWS::Serverless::Application 
    Properties:
      TimeoutInMinutes: 5
      Location: resources/custom-resources/waf-arn/template.yaml
      Parameters:
          ProjectName: !Ref ProjectName
          